run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main]

jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Start Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install

      - name: Build project
        run: npm run build

      - name: Lint code
        run: npm run lint